---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-cluster
  namespace: cnpg-cluster
spec:
  instances: 3

  storage:
    size: 4Gi

  monitoring:
    enablePodMonitor: true
  # PostgresConfiguration:
  #   pg_hba: 
  #     - host all all 0.0.0.0/0 md5