provider:
  name: aws

source:
  - ingress

policy: upsert-only

env:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/aws/credentials/credentials
extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns # In this example, the secret will have the data stored in a key named `credentials`
extraVolumeMounts:
  - name: aws-credentials
    mountPath: /etc/aws/credentials
    readOnly: true

# Note: Ensure you have created the secret with your AWS credentials before applying this configuration.
# Example command to create the secret:
# k create secret generic external-dns --from-file=credentials=~/.aws/credentials --namespace=external-dns