---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cloudzap
  namespace: development
spec:
  interval: 1m
  url: https://github.com/jgeissler14/open-react-site
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudzap
  namespace: development
spec:
  interval: 1m
  releaseName: cloudzap
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: cloudzap
  values:
    image:
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudzap-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudzap
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60