apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
  namespace: homepage
stringData:
  # kubernetes.yaml: |
  #   mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""


  services.yaml: |
    - Homelab:
        # - Pi-hole:
        #     href: "http://192.168.120.10:3009/admin"
        #     icon: pi-hole.png
        #     widget:
        #         type: pihole
        #         url: "http://192.168.120.10:3009"
        #         # version: 6 # required if running v6 or higher, defaults to 5
        #         key: PIHOLE_KEY_PLACEHOLDER
        # - Pgadmin:
        #     href: https://pgadmin.joshgeissler.com
        #     icon: pgadmin.png

        - Grafana:
            href: https://grafana.joshgeissler.com
            icon: grafana.png
        # - Backstage
        #     href: https://backstage.joshgeissler.com
        #     icon: backstage.png

        # - Synology:
        #     href: http://192.168.120.186:5000/
        #     icon: synology.png
        # - Transmission:
        #     href: http://192.168.120.186:3001/
        #     icon: transmission.png
        # - Unifi:
        #     href: https://unifi.ui.com/consoles/942A6F1064FA0000000007DE81DF0000000008475267000000006579C213:1019936139/network/default/dashboard
        #     description: Unifi
        #     icon: unifi.png
        # - Home Assistant:
        #     href: https://ass.joshgeissler.com
        #     description: Home Assistant
        #     icon: home-assistant.png

    - Work:
        - Outlook:
            href: https://teams.microsoft.com/v2/
            icon: outlook.png
        - Teams:
            href: https://teams.microsoft.com/v2/
            icon: teams.png

    - Creating:
        - YouTube:
            href: https://youtube.com
            icon: youtube.png
        - YouTube Studio:
            href: https://studio.youtube.com
            icon: youtube.png
        - LinkedIn:
            href: https://linkedin.com
            icon: linkedin.png
        - Skool:
            href: https://www.skool.com/
            icon: mdi-school-outline-#FFF200

    - Misc:
        - Claude:
            href: https://claude.ai/new
            icon: mdi-robot-excited-outline-#DE7552

  widgets.yaml: |
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    # - resources:
    #     backend: resources
    #     expanded: true
    #     cpu: true
    #     memory: true
    - calendar:
        firstDayInWeek: sunday # optional - defaults to monday
        view: monthly # optional - possible values monthly, agenda
        maxEvents: 10 # optional - defaults to 10
        showTime: true # optional - show time for event happening today - defaults to false
        timezone: America/Los_Angeles # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
        integrations: # optional
          - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
            service_group: Media # group name where widget exists
            service_name: Sonarr # service name for that widget
            color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            baseUrl: https://sonarr.domain.url # optional - adds links to sonarr/radarr pages
            params: # optional - additional params for the service
            unmonitored: true # optional - defaults to false, used with *arr stack
          - type: ical # Show calendar events from another service
            url: https://domain.url/with/link/to.ics # URL with calendar events
            name: My Events # required - name for these calendar events
            color: zinc # optional - defaults to pre-defined color for the service (zinc for ical)
            params: # optional - additional params for the service
            showName: true # optional - show name before event title in event line - defaults to false
    - search:
        provider: google
        target: _blank
    - weather:
        location: "Temecula, CA"
        units: metric # optional - defaults to imperial
        showForecast: true # optional - defaults to false
    - time:
        datetime: "" # optional - defaults to current time
        text_size: xl # optional - defaults to lg
  docker.yaml: ""
