apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
  namespace: homepage
stringData:
  kubernetes.yaml: |
    mode: cluster
  bookmarks.yaml: ""
  settings.yaml: |
    background: 
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    color: slate
    layout:
      Media:
      style: row
      columns: 4
    theme: dark
  custom.css: ""
  custom.js: ""


  services.yaml: |
    - Homelab:
        - Grafana:
            href: https://grafana.joshgeissler.com
            icon: grafana.png        
        - Backstage:
            href: https://backstage.joshgeissler.com
            icon: https://backstage.io/img/logo.svg
        - Container Platform:
            href: https://jobs.joshgeissler.com
            icon: https://icons.veryicon.com/png/o/miscellaneous/2022-complete-collection-of-alibaba-cloud/csk-container-service-kubernetes-edition-1.png
        # - Pi-hole:
        #     href: "http://192.168.120.10:3009/admin"
        #     icon: pi-hole.png
        #     widget:
        #         type: pihole
        #         url: "http://192.168.120.10:3009"
        #         # version: 6 # required if running v6 or higher, defaults to 5
        #         key: PIHOLE_KEY_PLACEHOLDER
        # - Pgadmin:
        #     href: https://pgadmin.joshgeissler.com
        #     icon: pgadmin.png
        # - Synology:
        #     href: http://192.168.120.186:5000/
        #     icon: synology.png
        # - Transmission:
        #     href: http://192.168.120.186:3001/
        #     icon: transmission.png
        # - Unifi:
        #     href: https://unifi.ui.com/consoles/942A6F1064FA0000000007DE81DF0000000008475267000000006579C213:1019936139/network/default/dashboard
        #     description: Unifi
        #     icon: unifi.png

    - Work:
        - Outlook:
            href: https://teams.microsoft.com
            icon: microsoft-outlook.png
        - Teams:
            href: https://teams.microsoft.com
            icon: microsoft-teams.png

    - Creating:
        - YouTube:
            href: https://youtube.com
            icon: youtube.png
        - YouTube Studio:
            href: https://studio.youtube.com
            icon: youtube.png
        - LinkedIn:
            href: https://linkedin.com
            icon: linkedin.png
        - Skool:
            href: https://www.skool.com/
            icon: mdi-school-outline-#FFF200

    - Misc:
        - ChatGPT:
            href: https://chatgpt.com/
            icon: openai-light.png

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true

    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: xl
        format:
            dateStyle: short
            timeStyle: short
            hour12: true
        
  docker.yaml: ""
