apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: grafana
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.59.4
    chart: grafana
    helm:
      releaseName: grafana
      values: |
        service:
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: grafana.geisslersolutions.com
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:285824578675:certificate/f226d2ef-7429-4bc6-b99a-55fdd33e904a"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
            service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true