apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-platform
  labels:
    app.kubernetes.io/name: job-platform
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jobs.joshgeissler.com
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jobs.joshgeissler.com
      secretName: job-platform-tls
  rules:
    - host: jobs.joshgeissler.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-platform-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: job-platform-backend
                port:
                  number: 80
