apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backstage
spec:
  interval: 24h
  url: https://backstage.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
spec:
  interval: 30m
  chart:
    spec:
      chart: backstage
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: backstage
      interval: 12h
  values:
    backstage:
      appConfig:
        techdocs:
          builder: "local"
        app:
          # Let's test that everything is fine with comments
          title: The very best Backstage Helm Chart! :D
          baseUrl: https://backstage.joshgeissler.com
        backend:
          baseUrl: https://backstage.joshgeissler.com
        auth:
          providers:
            guest:
              dangerouslyAllowOutsideDevelopment: true

    postgres:
      enabled: true
    ingress:
      enabled: true
      host: backstage.joshgeissler.com
      tls:
        enabled: true
        secretName: backstage-ingress
    metrics:
      serviceMonitor:
        enabled: true
        annotations:
          test: test
        labels:
          test: test
        path: /metrics
        port: http-backend