apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - backstage.yaml
configMapGenerator:
  - name: backstage-config
    files:
      - backstage-values.yaml