service:
  type: LoadBalancer
  port: 443
nextcloud:
  host: cloud.geisslersolutions.com



# NOTE: NextCloud helm chart DOES NOT have annotations added for the service
# I manually ran kubectl edit -n nextcloud svc nextcloud to add the annotations

  # external-dns.alpha.kubernetes.io/hostname: cloud.geisslersolutions.com
  # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:285824578675:certificate/fbf35d82-be5b-42c0-bf3c-66ab3a6b4606"
  # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  # service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
  