---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 24h
  url: https://backstage.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 30m
  chart:
    spec:
      chart: backstage
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: backstage
      interval: 12h