---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Replace the email address with your own contact email
    email: josh@cloudzap.co
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - dns01:
          route53:
            region: us-east-1 # Replace with your AWS region
            accessKeyIDSecretRef:
              name: cert-manager
              key: access-key-id
            secretAccessKeySecretRef:
              name: cert-manager
              key: secret-access-key
