apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - backstage-ingress.yaml
generatorOptions:
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: grafana-datasources
    namespace: kube-prometheus-stack
    files:
      - dashboard.json