apiVersion: v1
kind: Namespace
metadata:
  name: mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: mcp-server
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: ghcr.io/jgeissler14/homelab/browser:latest
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  labels:
    app.kubernetes.io/name: mcp-server
  annotations:
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mcp-server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-server
  labels:
    app.kubernetes.io/name: mcp-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mcp.joshgeissler.com
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: mcp.joshgeissler.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 8088
  tls:
    - hosts:
        - mcp.joshgeissler.com
      secretName: mcp-server-ingress
