---
apiVersion: v1
kind: Namespace
metadata:
  name: google
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: google
  namespace: google
spec:
  interval: 1m
  url: https://github.com/jgeissler14/google
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: google
  namespace: google
spec:
  interval: 1m
  releaseName: google
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: google
  values:
    image:
      tag: latest
  service:
    type: NodePort