---
apiVersion: v1
kind: Namespace
metadata:
  name: google
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: google-repo
  namespace: google
spec:
  interval: 1m
  url: https://github.com/jgeissler14/google
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: google-kustomization
  namespace: google
spec:
  interval: 5m
  path: "./helm"
  prune: true
  sourceRef:
    kind: GitRepository
    name: google-repo
    namespace: google
  validation: client