---
apiVersion: v1
kind: Namespace
metadata:
  name: google
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: google-repo
  namespace: google
spec:
  url: https://github.com/jgeissler14/google/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: google-release
  namespace: google
spec:
  releaseName: google
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: HelmRepository
        name: google-repo
        namespace: google
  interval: 20m # change to 1m for testing
  install:
    remediation:
      retries: 3