apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.guestbook.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.guestbook.spec.source.repoURL }}
    targetRevision: {{ .Values.guestbook.spec.source.targetRevision }}
    helm:
      releaseName: helm-guestbook
      valueFiles:
        - values.yaml
