name: Build and Push Browser Image

on:
  push:
    branches: [main]
    paths:
      - 'Docker/Dockerfile.browser'
      - '.github/workflows/build-browser-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/Dockerfile.browser
          push: true
          tags: ghcr.io/jgeissler14/homelab/browser:latest,ghcr.io/jgeissler14/homelab/browser:${{ github.sha }}
