name: Build and Push Job Platform Images

on:
  push:
    branches: [main]
    paths:
      - 'job-platform/backend/**'
      - 'job-platform/ui/**'
      - '.github/workflows/ghcr-build.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: backend
            context: job-platform/backend
            dockerfile: job-platform/backend/Dockerfile
          - image: frontend
            context: job-platform/ui
            dockerfile: job-platform/ui/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/jgeissler14/homelab/${{ matrix.image }}:latest,ghcr.io/jgeissler14/homelab/${{ matrix.image }}:${{ github.sha }}
